/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class part2 */

#ifndef _Included_part2
#define _Included_part2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     part2
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_part2_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
