/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class balayageK2_Interface */

#ifndef _Included_balayageK2_Interface
#define _Included_balayageK2_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     balayageK2_Interface
 * Method:    tests_calcul
 * Signature: (B[DDDDIIIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_balayageK2_Interface_tests_1calcul
  (JNIEnv *, jclass, jbyte, jdoubleArray, jdouble, jdouble, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
