/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class balayageK2_Interface */

#ifndef _Included_balayageK2_Interface
#define _Included_balayageK2_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     balayageK2_Interface
 * Method:    tests_calcul
 * Signature: (LbalayageK2/CalculCascade2D;[DDDDDDD)[I
 */
JNIEXPORT jintArray JNICALL Java_balayageK2_Interface_tests_1calcul
  (JNIEnv *, jclass, jobject, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     balayageK2_Interface
 * Method:    einit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_balayageK2_Interface_einit
  (JNIEnv *, jclass);

/*
 * Class:     balayageK2_Interface
 * Method:    eclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_balayageK2_Interface_eclose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
